FROM        buildbot/buildbot-worker:master
MAINTAINER  Buildbot maintainers

USER root

ADD https://github.com/jimmykim1/learning-buildbot/blob/master/Worker/buildbot.tac /buildbot/buildbot.tac

USER buildbot
